[package]
name = "cycle_time_tauri"
version = "0.0.1"
description = "Cycle Time Calculator"
edition = "2021"

[dependencies]
tauri = { version = "1", features = ["api-all"] }

[build-dependencies]
tauri-build = "1"
